set(V15_CONFIG "${CMAKE_CURRENT_SOURCE_DIR}/config/v15.json" CACHE FILEPATH "V1.5 配置")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${V15_CONFIG}"
  "${CMAKE_CURRENT_SOURCE_DIR}/config/v15.schema.json" "${CMAKE_CURRENT_SOURCE_DIR}/tools/configure_v15.py"
  "${CMAKE_CURRENT_SOURCE_DIR}/tools/v15_config_identity.py")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tools/configure_v15.py"
  "${V15_CONFIG}" "${CMAKE_CURRENT_BINARY_DIR}/generated/ship_perception/v15_config.hpp" RESULT_VARIABLE v15_result)
if(NOT v15_result EQUAL 0)
  message(FATAL_ERROR "V1.5 配置校验失败")
endif()
add_library(ship_structure src/structure/geometry_fit.cpp src/structure/offline_ship_frame.cpp src/structure/linear_structure_detector.cpp)
target_sources(ship_structure PRIVATE src/structure/topology_assembler.cpp src/structure/structural_recognizer.cpp)
target_include_directories(ship_structure PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}/generated")
target_link_libraries(ship_structure PUBLIC Eigen3::Eigen PRIVATE small_gicp_vendor)
add_library(ship_structure_io src/structure/model_io.cpp)
target_link_libraries(ship_structure_io PUBLIC ship_structure)
add_library(ship_structure_tracking src/structure/tracking_adapter.cpp)
target_link_libraries(ship_structure_tracking PUBLIC ship_structure ship_tracking)
add_executable(v15_recognize tools/v15_main.cpp)
target_link_libraries(v15_recognize PRIVATE ship_structure_io ship_pcd)
if(BUILD_TESTING)
  set(V15_DATA_ROOT "$ENV{SHIP_V15_DATA_ROOT}" CACHE PATH "只读真实数据根目录；默认 Quick 必需")
  add_executable(v15_integration tests/v15_integration.cpp)
  target_link_libraries(v15_integration PRIVATE ship_structure_tracking ship_structure_io)
  add_executable(v15_adapter tests/v15_adapter.cpp)
  target_link_libraries(v15_adapter PRIVATE ship_structure_tracking)
  add_test(NAME v15_adapter COMMAND v15_adapter)
  add_test(NAME v15_partial_annotation COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_v15_evaluation.py")
  add_test(NAME v15_pcd_decoder COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_v15_pcd.py")
  add_test(NAME v15_model_contract COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_v15_contracts.py")
  add_test(NAME v15_provenance COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_v15_provenance.py")
  add_test(NAME v15_configuration COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/test_v15_config.py")
  add_test(NAME v15r0_measurement COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_v15r0_measurement)
  set_tests_properties(v15r0_measurement PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_static COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_static)
  set_tests_properties(v15r1_static PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_heightmap_topology COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_heightmap_topology)
  set_tests_properties(v15r1_heightmap_topology PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_height_structure_forensics COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_height_structure_forensics)
  set_tests_properties(v15r1_height_structure_forensics PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_height_structure_forensics_p1 COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_height_structure_forensics_p1)
  set_tests_properties(v15r1_height_structure_forensics_p1 PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_plane_consensus COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_plane_consensus)
  set_tests_properties(v15r1_plane_consensus PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15r1_family_reference COMMAND "${Python3_EXECUTABLE}" -m unittest
    ship_perception.tests.test_r1_family_reference)
  set_tests_properties(v15r1_family_reference PROPERTIES WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")
  add_test(NAME v15_gt_isolation COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tools/run_v15_isolation.py" "$<TARGET_FILE:v15_recognize>")
  add_executable(v15_grid_phase tests/v15_grid_phase.cpp)
  target_link_libraries(v15_grid_phase PRIVATE ship_structure)
  add_test(NAME v15_grid_phase COMMAND v15_grid_phase)
  add_executable(v15_frame tests/v15_frame.cpp)
  target_link_libraries(v15_frame PRIVATE ship_structure)
  add_test(NAME v15_frame COMMAND v15_frame)
  add_executable(v15_geometry tests/v15_geometry.cpp)
  target_link_libraries(v15_geometry PRIVATE ship_structure)
  add_test(NAME v15_geometry COMMAND v15_geometry)
  add_test(NAME v14_frozen_paths COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tools/verify_v14_frozen.py")
  add_test(NAME v15_quick COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tools/run_v15_quick.py"
    --recognizer "$<TARGET_FILE:v15_recognize>" --integration "$<TARGET_FILE:v15_integration>"
    --data-root "${V15_DATA_ROOT}" --output "${CMAKE_CURRENT_BINARY_DIR}/artifacts/v15_quick")
  set_tests_properties(v15_quick PROPERTIES LABELS "v15;quick_acceptance" TIMEOUT 7500)
  if(NOT V15_DATA_ROOT)
    message(STATUS "V1.5 Quick 真实数据未配置：请设置 V15_DATA_ROOT；仅运行单元回归时使用 ctest -LE quick_acceptance")
  endif()
endif()
